FROM registry.ocp4.example.com:8443/ubi8/ubi

RUN yum --disableplugin=subscription-manager -y module enable php:7.4 \
  && yum --disableplugin=subscription-manager -y install httpd php \
  && yum --disableplugin=subscription-manager clean all

ADD index.php /var/www/html

RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/www/html /var/log/httpd /var/run/httpd /run/php-fpm \
  && chmod -R g=u /var/www/html/ /var/log/httpd /var/run/httpd /run/php-fpm

EXPOSE 8080

USER 1001

CMD php-fpm -D ; httpd -D FOREGROUND