apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: versioned-hello
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.ocp4.example.com:8443/redhattraining/versioned-hello:1-123
    name: "1"
