apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: version
      name: version
    spec:
      replicas: 10
      selector:
        matchLabels:
          app: version
      template:
        metadata:
          labels:
            app: version
        spec:
          containers:
          - image: versioned-hello:1
            name: versioned-hello
            readinessProbe:
              failureThreshold: 3
              initialDelaySeconds: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: version
      name: version
    spec:
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: version

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: version
      name: version
    spec:
      host: version-updates-triggers.apps.ocp4.example.com
      to:
        kind: Service
        name: version
        weight: 100
      ports:
        targetPort: 8080
      selector:
        app: version
