apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: longload
      name: longload
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: longload
      template:
        metadata:
          labels:
            app: longload
        spec:
          containers:
          - image: registry.ocp4.example.com:8443/redhattraining/long-load:v1
            name: longload
            env:
            - name: START_DELAY
              value: "7000"
            - name: SHOW_HOST
              value: "true"
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 3000
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 3000
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                cpu: 100m

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: longload
      name: longload
    spec:
      ports:
      - port: 3000
        protocol: TCP
        targetPort: 3000
      selector:
        app: longload
      type: NodePort
