apiVersion: apps/v1
kind: Deployment
metadata:
  name: long-load
  labels:
    app: long-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: long-load
  template:
    metadata:
      labels:
        app: long-load
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/redhattraining/long-load:v1
        imagePullPolicy: Always
        name: long-load
        env:
        - name: START_DELAY
          value: "60000"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: long-load
  labels:
    app: long-load
spec:
  selector:
    app: long-load
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: long-load
  labels:
    app: long-load
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: long-load
