apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: loadtest
      name: loadtest
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: loadtest
      template:
        metadata:
          labels:
            app: loadtest
        spec:
          containers:
          - image: registry.ocp4.example.com:8443/redhattraining/loadtest:v1.0
            name: loadtest
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /api/loadtest/v1/healthz
                port: 8080
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              requests:
                cpu: 25m
              limits:
                cpu: 100m

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: loadtest
      name: loadtest
    spec:
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: loadtest

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: loadtest
      name: loadtest
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: loadtest
